[package]
name = "zj-which-key"
version = "0.1.0"
edition = "2024"

[dependencies]
zellij-tile = "0.43"
serde = { version = "1.0", features = ["derive"] }
ansi_term = "0.12"

[profile.release]
opt-level = "z"
lto = true
strip = true
